### ISSUE TITLE
Duration: Refine and design anomaly detection workflow

### ISSUE THREAD

**Issue by nadinevehling** [grafana/traces-drilldown#38]
We have a rough concept of how the user workflow may look like. 

When a user has arrived at this stage of the app, they have:
1. Already determined an analysis type: Primary signal (server spans, consumer spans, db calls, etc)
2. Already determined a metric type (rate/errors/duration) 
3. Already narrowed down their attribute filters
4. Moved on to the second page

Now, we want to answer questions related to 3 scenarios (Rate, Errors, Duration):

[Figma](https://www.figma.com/design/GcixZJYCEqy7CGqEou1Zbt/Workflows?node-id=145-4236&t=W77i9AvtBxUZMLzy-0)
[Design Doc](https://docs.google.com/document/d/10xNlcIupzvB8Vu4BVWdUPp9lVJZL9xCYHkaRokYrj4A/edit)

```[tasklist]
### Tasks in order of workflow
- [x] Discoverability: How can we provide guidance and guardrails for users to discover the flow?
- [x] Interaction: What interaction and content does the datatip showcase?
- [x] Interaction: How does it work in detail? How can we guide users along the workflow?
- [x] Compare: How does the step after selecting a box work?
- [x] Goal: What are the next steps? How can we provide more guidance on next steps?
- [x] Add trace table to value card
- [ ] https://github.com/grafana/explore-traces/issues/61
- [ ] https://github.com/grafana/explore-traces/issues/62
```
